// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlmwayixattwcyklncvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sbXdheWl4YXR0d2N5a2xuY3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4Njk2MzUsImV4cCI6MjA2MjQ0NTYzNX0.dEngGw20gpaYtE5c5IwHYumXKE-R3P7J4s31UtAOxW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);